In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas 
close_prices_data = pandas.read_csv('/content/drive/My Drive/sales_train.csv', date_parser='date')
shops_data = pandas.read_csv('/content/drive/My Drive/shops.csv')
items_data = pandas.read_csv('/content/drive/My Drive/items.csv')
items_categories_data = pandas.read_csv('/content/drive/My Drive/item_categories.csv')

In [3]:
close_prices_data = close_prices_data.join(close_prices_data['date'].str.split(r'\.|,', expand=True))
del close_prices_data['date']
close_prices_data = close_prices_data.rename(columns={ close_prices_data.columns[5]: "day" , close_prices_data.columns[6]: "month",close_prices_data.columns[7]: "year" })
close_prices_data['month'] = pandas.to_numeric(close_prices_data['month'], errors='coerce')
close_prices_data['year'] = pandas.to_numeric(close_prices_data['year'], errors='coerce')
close_prices_data

         date_block_num  shop_id  item_id  ...  day  month  year
0                     0       59    22154  ...   02      1  2013
1                     0       25     2552  ...   03      1  2013
2                     0       25     2552  ...   05      1  2013
3                     0       25     2554  ...   06      1  2013
4                     0       25     2555  ...   15      1  2013
...                 ...      ...      ...  ...  ...    ...   ...
2935844              33       25     7409  ...   10     10  2015
2935845              33       25     7460  ...   09     10  2015
2935846              33       25     7459  ...   14     10  2015
2935847              33       25     7440  ...   22     10  2015
2935848              33       25     7460  ...   03     10  2015

[2935849 rows x 8 columns]

In [4]:
import numpy as np

#SALE_TABLE = 
_ID_ITEM_ = np.array([i%len(items_data) for i in range(len(shops_data) * len(items_data) * len(close_prices_data['date_block_num'].unique()))])

In [5]:
_BLOCK_ = np.array([  i//len(items_data)  for j in range(len(shops_data)) for i in range(len(items_data) * len(close_prices_data['date_block_num'].unique()))  ])

In [6]:
LEN = (len(items_data) * len(close_prices_data['date_block_num'].unique()))
_ID_SHOP_ = np.array([i//LEN for i in range(len(shops_data) * len(items_data) * len(close_prices_data['date_block_num'].unique()))])

In [7]:
dictionary_pandas = {'ID_item': _ID_ITEM_, 'BLOCK': _BLOCK_, 'ID_SHOP': _ID_SHOP_}
print(len(_ID_ITEM_),len(_BLOCK_))

PD_PRICE_ID_SHOP = pandas.DataFrame(dictionary_pandas)

PD_PRICE_ID_SHOP[PD_PRICE_ID_SHOP['BLOCK']==1]

45226800 45226800

          ID_item  BLOCK  ID_SHOP
22170           0      1        0
22171           1      1        0
22172           2      1        0
22173           3      1        0
22174           4      1        0
...           ...    ...      ...
44517355    22165      1       59
44517356    22166      1       59
44517357    22167      1       59
44517358    22168      1       59
44517359    22169      1       59

[1330200 rows x 3 columns]

In [13]:
LEN1 = len(shops_data) * len(items_data) * len(close_prices_data['date_block_num'].unique())
PRICE_SHOP_ = np.array([0 for i in range(LEN1)])
COUNT_BUY_SHOP = np.array([0 for i in range(LEN1)])

In [34]:
import warnings
warnings.filterwarnings('ignore')
import time

MONTH_CHECK_DELETE = [5,10,15,20,25,30,33]
TIME = time.time()
PD_PRICE_ID_SHOP['PRICE'] = 0
PD_PRICE_ID_SHOP['COUNT_BUY'] = 0 
#SUM_SALE_ITEM_PRICE = 0
#SUM_SALE_ITEM = 0
ACTIVE_PRICE = 0
LEN_FOR_K = len(shops_data)
LEN_FOR_J = len(close_prices_data['date_block_num'].unique())
LEN_FOR_I = len(items_data)

_PRICE_ = np.array([])
_COUNT_BUY_ = np.array([])

_PRICE_FILLED = np.array([])
_COUNT_BUY_FILLED = np.array([])

for k in range(LEN_FOR_K):

  close_prices_data_K = close_prices_data[close_prices_data['shop_id'] == k]
  print('â„–K',k)

  for j in range(LEN_FOR_J):
    

    close_prices_data_J = close_prices_data_K[close_prices_data_K['date_block_num'] == j]
    print('â„–J',j, 'time', TIME - time.time())

    for i in range(LEN_FOR_I):

      close_prices_data_I = close_prices_data_J[close_prices_data_J['item_id'] == i]

      if i == 100:
        print('â„–i',i, 'time', TIME - time.time())
      SUM_SALE_ITEM_PRICE = (close_prices_data_I['item_price'] * close_prices_data_I[
          'item_cnt_day']).sum()
      SUM_SALE_ITEM = close_prices_data_I[
          'item_cnt_day'].sum()
      _COUNT_BUY_ = np.append(_COUNT_BUY_,SUM_SALE_ITEM)

      #INDEX_PD = PD_PRICE_ID_SHOP[PD_PRICE_ID_SHOP['BLOCK'] == j][PD_PRICE_ID_SHOP['ID_SHOP'] == k][PD_PRICE_ID_SHOP['ID_item'] == i].index.to_numpy()   *************
      #if len(INDEX_PD) > 1:                                                      *************
        #print('Ð¿Ñ€Ð¾Ð¸Ð·Ð¾ÑˆÐ»Ð° Ð¾ÑˆÐ¸Ð±ÐºÐ° â„–1')                                             *************
        #break;                                                                   *************
      #COUNT_BUY_SHOP[INDEX_PD[0]] = SUM_SALE_ITEM   
      #PD_PRICE_ID_SHOP['COUNT_BUY'][INDEX_PD[0]] = SUM_SALE_ITEM                 *************

      COSTS = close_prices_data_I['item_price'].index.to_numpy()
      if COSTS.size != 0:
        ACTIVE_PRICE = COSTS[-1]

      if SUM_SALE_ITEM != 0:
        WEIGHTED_AVERAGE_COST = SUM_SALE_ITEM_PRICE / SUM_SALE_ITEM
        #PRICE_SHOP_[INDEX_PD[0]] = WEIGHTED_AVERAGE_COST
        _PRICE_ = np.append(_PRICE_,WEIGHTED_AVERAGE_COST)
        #PD_PRICE_ID_SHOP['PRICE'][INDEX_PD[0]] = WEIGHTED_AVERAGE_COST           *************
      else:
        #PRICE_SHOP_[INDEX_PD[0]] = ACTIVE_PRICE                   
        _PRICE_ = np.append(_PRICE_,ACTIVE_PRICE)
        #PD_PRICE_ID_SHOP['PRICE'][INDEX_PD[0]] = ACTIVE_PRICE                    *************
    _PRICE_FILLED = np.append(_PRICE_FILLED, _PRICE_)
    _COUNT_BUY_FILLED = np.append(_COUNT_BUY_FILLED, _COUNT_BUY_)
    _PRICE_ = np.array([])
    _COUNT_BUY_ = np.array([])
    if i in MONTH_CHECK_DELETE:
      _PRICE_FILLED_2 = np.append(_PRICE_FILLED_2, _PRICE_FILLED)
      _COUNT_BUY_FILLED_2 = np.append(_COUNT_BUY_FILLED_2, _COUNT_BUY_FILLED)
      _PRICE_FILLED = np.array([])
      _COUNT_BUY_FILLED = np.array([])

#SUM_SALE_ITEM_PRICE = 0
#SUM_SALE_ITEM = 0

â„–K 0
â„–J 0 time -0.24892711639404297
â„–i 100 time -0.40087461471557617
â„–J 1 time -25.26470923423767
â„–i 100 time -25.40256929397583

KeyboardInterrupt: ignored

In [24]:
import numpy as np
_ID_ = np.array([])
_PRICE_ = np.array([])
_COUNT_BUY_ = np.array([])
_BLOCK_ = np.array([])
_BLOCK_MONTH_ = np.array([])
_BLOCK_YEAR_ = np.array([])
_CATEGORY_ = np.array([])
TIME = time.time()
for I in range(len(shops_data)):
  PD_price_ = close_prices_data[close_prices_data['shop_id'] == I] 
  
  for i in range(15):
    print('â„–i',i, 'time', TIME - time.time())
    PD_price = PD_price_[PD_price_['date_block_num'] == i] 
    for j in range(len(items_data)):
      if j == 100:
        print('â„–i',j, 'time', TIME - time.time())
      price = PD_price['item_price'][PD_price['item_id'] == j].unique()
    
      if price.size == 0:
        CATEGORY = items_data['item_category_id'][items_data['item_id']==j][j]
        _ID_ = np.append(_ID_,j)
        if i ==0:
          _PRICE_ = np.append(_PRICE_, 0)
        else:
          _PRICE_ = np.append(_PRICE_, _PRICE_[j+len(items_data)*(i - 1)])
        _COUNT_BUY_ = np.append(_COUNT_BUY_, 0)
        _BLOCK_ = np.append(_BLOCK_, i)
        _BLOCK_MONTH_ = np.append(_BLOCK_MONTH_, i%12+1)
        _BLOCK_YEAR_ = np.append(_BLOCK_YEAR_, i//12+2013)
        _CATEGORY_ = np.append(_CATEGORY_,CATEGORY)
      else:  
        BUY = PD_price['item_cnt_day'][PD_price['item_id'] == j].sum()
        if BUY != 0:
          PRICE_MEAN = ( PD_price['item_price'][PD_price['item_id'] == j]  * PD_price['item_cnt_day'][PD_price['item_id'] == j] ).sum() / PD_price['item_cnt_day'][PD_price['item_id'] == j].sum()
        else:

          PRICE_MEAN = PD_price['item_price'][PD_price['item_id'] == j].sum()/ len(PD_price['item_price'][PD_price['item_id'] == j]) 
      #for a in range(len(price)):
        #PRICE =  PD_price['item_cnt_day'][PD_price['item_price'] == price[a] ][PD_price['item_id'] == j].sum()
        CATEGORY = items_data['item_category_id'][items_data['item_id']==j][j]
        _ID_ = np.append(_ID_,j)
      #_PRICE_ = np.append(_PRICE_, price[a])
      #_COUNT_BUY_ = np.append(_COUNT_BUY_, PRICE) 
        _PRICE_ = np.append(_PRICE_, PRICE_MEAN) 
        _COUNT_BUY_ = np.append(_COUNT_BUY_, BUY)
        _BLOCK_ = np.append(_BLOCK_, i)
        _BLOCK_MONTH_ = np.append(_BLOCK_MONTH_, i%12+1)
        _BLOCK_YEAR_ = np.append(_BLOCK_YEAR_, i//12+2013)
        _CATEGORY_ = np.append(_CATEGORY_,CATEGORY)
        

dictionary_pandas = {'ID_item': _ID_, 'PRICE': _PRICE_, 'BLOCK': _BLOCK_,'BLOCK_MONTH': _BLOCK_MONTH_, 'BLOCK_YEAR': _BLOCK_YEAR_, 'CATEGORY': _CATEGORY_, 'COUNT_BUY': _COUNT_BUY_}
PD_PRICE_ID_SHOP = pandas.DataFrame(dictionary_pandas)
PD_PRICE_ID_SHOP['BLOCK_MONTH']

â„–i 0 time -0.009619712829589844
â„–i 100 time -0.13553214073181152
â„–i 1 time -28.583631992340088
â„–i 100 time -28.735292434692383

KeyboardInterrupt: ignored